# Generated by Django 3.2.7 on 2021-12-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='care_yn',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='semester',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
